"""FastAPI dependency injection.

Provides reusable dependencies for:
- Database sessions
- Authentication/authorization
- Idempotency handling
- Services

Following dependency injection principles:
- Dependencies are provided, not created, by the function
- Testing can substitute any dependency with a mock
"""

from collections.abc import Generator
from typing import Any

from fastapi import Header, HTTPException, Request, Depends
from sqlalchemy.orm import Session

from app.db.session import get_db
from app.db.unit_of_work import UnitOfWork


def get_idempotency_key(
    idempotency_key: str | None = Header(None, alias="Idempotency-Key"),
) -> str | None:
    """Extract the idempotency key from request headers.

    The Idempotency-Key header is required for all money-moving operations.
    It should be a unique value (typically a UUID v4) generated by the client.
    """
    return idempotency_key


def get_client_ip(request: Request) -> str | None:
    """Extract client IP from request for audit logging."""
    forwarded = request.headers.get("X-Forwarded-For")
    if forwarded:
        return forwarded.split(",")[0].strip()
    return request.client.host if request.client else None


def get_current_user(
    db: Session = Depends(get_db),
    user_id: str | None = Header(None, alias="X-User-Id"),
) -> Any:
    """Mock authentication — extracts user ID from header.

    In production, this would validate a JWT token, session cookie,
    or API key. For this assignment, we use a header-based approach.

    IMPORTANT: This is a mock. In production, use OAuth2/JWT.
    """
    if not user_id:
        raise HTTPException(
            status_code=401,
            detail="Missing X-User-Id header (mock auth)",
        )
    # Validate user exists
    from app.db.repositories.user_repo import UserRepository

    repo = UserRepository(db)
    user = repo.get(user_id)
    if not user:
        raise HTTPException(
            status_code=401,
            detail="User not found",
        )
    return user


def get_admin_user(
    db: Session = Depends(get_db),
    user_id: str | None = Header(None, alias="X-User-Id"),
    admin_key: str | None = Header(None, alias="X-Admin-Key"),
) -> Any:
    """Mock admin authentication.

    In production, this would verify admin role from JWT claims.
    """
    from app.core.enums import UserStatus

    if not user_id:
        raise HTTPException(status_code=401, detail="Missing X-User-Id header")

    from app.db.repositories.user_repo import UserRepository

    repo = UserRepository(db)
    user = repo.get(user_id)
    if not user:
        raise HTTPException(status_code=401, detail="User not found")

    # In production, check admin role from JWT or database
    if admin_key != "admin-secret-key":
        raise HTTPException(status_code=403, detail="Admin access required")

    return user


def get_uow(db: Session = Depends(get_db)) -> Generator[UnitOfWork, None, None]:
    """Provide a Unit of Work instance."""
    uow = UnitOfWork(db)
    try:
        yield uow
    finally:
        pass  # Session is managed by get_db
